# Generated by Django 2.2.2 on 2019-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/profile_pics/default.jpg', upload_to='images/profile_pics'),
        ),
    ]
