# Generated by Django 2.2.2 on 2019-07-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190704_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='images/game_profile/default.png', upload_to='images/game_profile')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_username', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_games',
            field=models.ManyToManyField(through='accounts.UserId', to='accounts.Game', verbose_name='games subcribed'),
        ),
    ]
