# Generated by Django 2.2.2 on 2019-07-05 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190705_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribed_games',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Game'),
        ),
    ]
