# Generated by Django 2.2.2 on 2019-07-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190705_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
